/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsocketAdapterRouteImport } from './routes/websocket-adapter'
import { Route as ToolsTestRouteImport } from './routes/tools-test'
import { Route as PersistenceDurabilityRouteImport } from './routes/persistence-durability'
import { Route as MiddlewareTestRouteImport } from './routes/middleware-test'
import { Route as MarkdownCjkRouteImport } from './routes/markdown-cjk'
import { Route as JoinRunClientToolRouteImport } from './routes/join-run-client-tool'
import { Route as InterruptsTestRouteImport } from './routes/interrupts-test'
import { Route as GenerationPersistenceServerRouteImport } from './routes/generation-persistence-server'
import { Route as GenerationPersistenceResumeRouteImport } from './routes/generation-persistence-resume'
import { Route as ForeignInterruptRouteImport } from './routes/foreign-interrupt'
import { Route as DevtoolsToolsRouteImport } from './routes/devtools-tools'
import { Route as DevtoolsStructuredRouteImport } from './routes/devtools-structured'
import { Route as DevtoolsRouteBRouteImport } from './routes/devtools-route-b'
import { Route as DevtoolsRouteARouteImport } from './routes/devtools-route-a'
import { Route as DevtoolsMemoryRouteImport } from './routes/devtools-memory'
import { Route as DevtoolsGenerationHooksRouteImport } from './routes/devtools-generation-hooks'
import { Route as DevtoolsChatRouteImport } from './routes/devtools-chat'
import { Route as ChatClientDefaultBridgeRouteImport } from './routes/chat-client-default-bridge'
import { Route as ByokRouteImport } from './routes/byok'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProviderIndexRouteImport } from './routes/$provider/index'
import { Route as ApiVideoRouteImport } from './routes/api.video'
import { Route as ApiTtsRouteImport } from './routes/api.tts'
import { Route as ApiTranscriptionRouteImport } from './routes/api.transcription'
import { Route as ApiToolsTestRouteImport } from './routes/api.tools-test'
import { Route as ApiToolCallLifecycleWireRouteImport } from './routes/api.tool-call-lifecycle-wire'
import { Route as ApiSummarizeRouteImport } from './routes/api.summarize'
import { Route as ApiSandboxToolHistoryRouteImport } from './routes/api.sandbox-tool-history'
import { Route as ApiSandboxFilePersistenceRouteImport } from './routes/api.sandbox-file-persistence'
import { Route as ApiSandboxDurabilityRouteImport } from './routes/api.sandbox-durability'
import { Route as ApiProviderToolDispatchWireRouteImport } from './routes/api.provider-tool-dispatch-wire'
import { Route as ApiPersistenceDurabilityRouteImport } from './routes/api.persistence-durability'
import { Route as ApiOtelUsageRouteImport } from './routes/api.otel-usage'
import { Route as ApiOtelTranscriptionRouteImport } from './routes/api.otel-transcription'
import { Route as ApiOtelMediaRouteImport } from './routes/api.otel-media'
import { Route as ApiOpenrouterWebToolsWireRouteImport } from './routes/api.openrouter-web-tools-wire'
import { Route as ApiOpenrouterReasoningWireRouteImport } from './routes/api.openrouter-reasoning-wire'
import { Route as ApiOpenrouterJsonObjectWireRouteImport } from './routes/api.openrouter-json-object-wire'
import { Route as ApiOpenrouterCostRouteImport } from './routes/api.openrouter-cost'
import { Route as ApiOpenaiUsageDetailsRouteImport } from './routes/api.openai-usage-details'
import { Route as ApiOpenaiStrictToolNullWireRouteImport } from './routes/api.openai-strict-tool-null-wire'
import { Route as ApiOpenaiShellSkillsWireRouteImport } from './routes/api.openai-shell-skills-wire'
import { Route as ApiOpenaiCompletedResponseTextRouteImport } from './routes/api.openai-completed-response-text'
import { Route as ApiNonStreamingRunErrorRouteImport } from './routes/api.non-streaming-run-error'
import { Route as ApiMultimodalToolResultWireRouteImport } from './routes/api.multimodal-tool-result-wire'
import { Route as ApiMistralStrictToolNullWireRouteImport } from './routes/api.mistral-strict-tool-null-wire'
import { Route as ApiMiddlewareTestRouteImport } from './routes/api.middleware-test'
import { Route as ApiMessageIdsRouteImport } from './routes/api.message-ids'
import { Route as ApiMcpTestRouteImport } from './routes/api.mcp-test'
import { Route as ApiMcpStatusTestRouteImport } from './routes/api.mcp-status-test'
import { Route as ApiMcpServerRouteImport } from './routes/api.mcp-server'
import { Route as ApiMcpManagedTestRouteImport } from './routes/api.mcp-managed-test'
import { Route as ApiMcpLifecycleTestRouteImport } from './routes/api.mcp-lifecycle-test'
import { Route as ApiMcpAppsServerRouteImport } from './routes/api.mcp-apps-server'
import { Route as ApiMcpAppsChatRouteImport } from './routes/api.mcp-apps-chat'
import { Route as ApiMcpAppsCallRouteImport } from './routes/api.mcp-apps-call'
import { Route as ApiMaxToolCallsWireRouteImport } from './routes/api.max-tool-calls-wire'
import { Route as ApiLazyToolsWireRouteImport } from './routes/api.lazy-tools-wire'
import { Route as ApiJoinRunClientToolRouteImport } from './routes/api.join-run-client-tool'
import { Route as ApiInterruptsTestRouteImport } from './routes/api.interrupts-test'
import { Route as ApiImageRouteImport } from './routes/api.image'
import { Route as ApiGenerationPersistenceServerRouteImport } from './routes/api.generation-persistence-server'
import { Route as ApiGenerationPersistenceResumeRouteImport } from './routes/api.generation-persistence-resume'
import { Route as ApiGeminiNativeImageWireRouteImport } from './routes/api.gemini-native-image-wire'
import { Route as ApiGeminiImageGaModelsRouteImport } from './routes/api.gemini-image-ga-models'
import { Route as ApiForeignInterruptRouteImport } from './routes/api.foreign-interrupt'
import { Route as ApiEmbeddingRouteImport } from './routes/api.embedding'
import { Route as ApiDurableTakeoverRouteImport } from './routes/api.durable-takeover'
import { Route as ApiDurableDeliveryRouteImport } from './routes/api.durable-delivery'
import { Route as ApiDevtoolsMemoryRouteImport } from './routes/api.devtools-memory'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiByokChatRouteImport } from './routes/api.byok-chat'
import { Route as ApiByteplusSeedance1080pWireRouteImport } from './routes/api.byteplus-seedance-1080p-wire'
import { Route as ApiAudioRouteImport } from './routes/api.audio'
import { Route as ApiArktypeToolWireRouteImport } from './routes/api.arktype-tool-wire'
import { Route as ApiAnthropicStructuredUsageRouteImport } from './routes/api.anthropic-structured-usage'
import { Route as ApiAnthropicSkillsWireRouteImport } from './routes/api.anthropic-skills-wire'
import { Route as ApiAnthropicBugTestRouteImport } from './routes/api.anthropic-bug-test'
import { Route as ProviderFeatureRouteImport } from './routes/$provider/$feature'
import { Route as ApiVideoStreamRouteImport } from './routes/api.video.stream'
import { Route as ApiTtsStreamRouteImport } from './routes/api.tts.stream'
import { Route as ApiTranscriptionStreamRouteImport } from './routes/api.transcription.stream'
import { Route as ApiImageStreamRouteImport } from './routes/api.image.stream'
import { Route as ApiAudioStreamRouteImport } from './routes/api.audio.stream'

const WebsocketAdapterRoute = WebsocketAdapterRouteImport.update({
  id: '/websocket-adapter',
  path: '/websocket-adapter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTestRoute = ToolsTestRouteImport.update({
  id: '/tools-test',
  path: '/tools-test',
  getParentRoute: () => rootRouteImport,
} as any)
const PersistenceDurabilityRoute = PersistenceDurabilityRouteImport.update({
  id: '/persistence-durability',
  path: '/persistence-durability',
  getParentRoute: () => rootRouteImport,
} as any)
const MiddlewareTestRoute = MiddlewareTestRouteImport.update({
  id: '/middleware-test',
  path: '/middleware-test',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkdownCjkRoute = MarkdownCjkRouteImport.update({
  id: '/markdown-cjk',
  path: '/markdown-cjk',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRunClientToolRoute = JoinRunClientToolRouteImport.update({
  id: '/join-run-client-tool',
  path: '/join-run-client-tool',
  getParentRoute: () => rootRouteImport,
} as any)
const InterruptsTestRoute = InterruptsTestRouteImport.update({
  id: '/interrupts-test',
  path: '/interrupts-test',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerationPersistenceServerRoute =
  GenerationPersistenceServerRouteImport.update({
    id: '/generation-persistence-server',
    path: '/generation-persistence-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const GenerationPersistenceResumeRoute =
  GenerationPersistenceResumeRouteImport.update({
    id: '/generation-persistence-resume',
    path: '/generation-persistence-resume',
    getParentRoute: () => rootRouteImport,
  } as any)
const ForeignInterruptRoute = ForeignInterruptRouteImport.update({
  id: '/foreign-interrupt',
  path: '/foreign-interrupt',
  getParentRoute: () => rootRouteImport,
} as any)
const DevtoolsToolsRoute = DevtoolsToolsRouteImport.update({
  id: '/devtools-tools',
  path: '/devtools-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const DevtoolsStructuredRoute = DevtoolsStructuredRouteImport.update({
  id: '/devtools-structured',
  path: '/devtools-structured',
  getParentRoute: () => rootRouteImport,
} as any)
const DevtoolsRouteBRoute = DevtoolsRouteBRouteImport.update({
  id: '/devtools-route-b',
  path: '/devtools-route-b',
  getParentRoute: () => rootRouteImport,
} as any)
const DevtoolsRouteARoute = DevtoolsRouteARouteImport.update({
  id: '/devtools-route-a',
  path: '/devtools-route-a',
  getParentRoute: () => rootRouteImport,
} as any)
const DevtoolsMemoryRoute = DevtoolsMemoryRouteImport.update({
  id: '/devtools-memory',
  path: '/devtools-memory',
  getParentRoute: () => rootRouteImport,
} as any)
const DevtoolsGenerationHooksRoute = DevtoolsGenerationHooksRouteImport.update({
  id: '/devtools-generation-hooks',
  path: '/devtools-generation-hooks',
  getParentRoute: () => rootRouteImport,
} as any)
const DevtoolsChatRoute = DevtoolsChatRouteImport.update({
  id: '/devtools-chat',
  path: '/devtools-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatClientDefaultBridgeRoute = ChatClientDefaultBridgeRouteImport.update({
  id: '/chat-client-default-bridge',
  path: '/chat-client-default-bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const ByokRoute = ByokRouteImport.update({
  id: '/byok',
  path: '/byok',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderIndexRoute = ProviderIndexRouteImport.update({
  id: '/$provider/',
  path: '/$provider/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoRoute = ApiVideoRouteImport.update({
  id: '/api/video',
  path: '/api/video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscriptionRoute = ApiTranscriptionRouteImport.update({
  id: '/api/transcription',
  path: '/api/transcription',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToolsTestRoute = ApiToolsTestRouteImport.update({
  id: '/api/tools-test',
  path: '/api/tools-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToolCallLifecycleWireRoute =
  ApiToolCallLifecycleWireRouteImport.update({
    id: '/api/tool-call-lifecycle-wire',
    path: '/api/tool-call-lifecycle-wire',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSummarizeRoute = ApiSummarizeRouteImport.update({
  id: '/api/summarize',
  path: '/api/summarize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSandboxToolHistoryRoute = ApiSandboxToolHistoryRouteImport.update({
  id: '/api/sandbox-tool-history',
  path: '/api/sandbox-tool-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSandboxFilePersistenceRoute =
  ApiSandboxFilePersistenceRouteImport.update({
    id: '/api/sandbox-file-persistence',
    path: '/api/sandbox-file-persistence',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSandboxDurabilityRoute = ApiSandboxDurabilityRouteImport.update({
  id: '/api/sandbox-durability',
  path: '/api/sandbox-durability',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProviderToolDispatchWireRoute =
  ApiProviderToolDispatchWireRouteImport.update({
    id: '/api/provider-tool-dispatch-wire',
    path: '/api/provider-tool-dispatch-wire',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPersistenceDurabilityRoute =
  ApiPersistenceDurabilityRouteImport.update({
    id: '/api/persistence-durability',
    path: '/api/persistence-durability',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOtelUsageRoute = ApiOtelUsageRouteImport.update({
  id: '/api/otel-usage',
  path: '/api/otel-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOtelTranscriptionRoute = ApiOtelTranscriptionRouteImport.update({
  id: '/api/otel-transcription',
  path: '/api/otel-transcription',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOtelMediaRoute = ApiOtelMediaRouteImport.update({
  id: '/api/otel-media',
  path: '/api/otel-media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenrouterWebToolsWireRoute =
  ApiOpenrouterWebToolsWireRouteImport.update({
    id: '/api/openrouter-web-tools-wire',
    path: '/api/openrouter-web-tools-wire',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOpenrouterReasoningWireRoute =
  ApiOpenrouterReasoningWireRouteImport.update({
    id: '/api/openrouter-reasoning-wire',
    path: '/api/openrouter-reasoning-wire',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOpenrouterJsonObjectWireRoute =
  ApiOpenrouterJsonObjectWireRouteImport.update({
    id: '/api/openrouter-json-object-wire',
    path: '/api/openrouter-json-object-wire',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOpenrouterCostRoute = ApiOpenrouterCostRouteImport.update({
  id: '/api/openrouter-cost',
  path: '/api/openrouter-cost',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenaiUsageDetailsRoute = ApiOpenaiUsageDetailsRouteImport.update({
  id: '/api/openai-usage-details',
  path: '/api/openai-usage-details',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenaiStrictToolNullWireRoute =
  ApiOpenaiStrictToolNullWireRouteImport.update({
    id: '/api/openai-strict-tool-null-wire',
    path: '/api/openai-strict-tool-null-wire',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOpenaiShellSkillsWireRoute =
  ApiOpenaiShellSkillsWireRouteImport.update({
    id: '/api/openai-shell-skills-wire',
    path: '/api/openai-shell-skills-wire',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOpenaiCompletedResponseTextRoute =
  ApiOpenaiCompletedResponseTextRouteImport.update({
    id: '/api/openai-completed-response-text',
    path: '/api/openai-completed-response-text',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiNonStreamingRunErrorRoute = ApiNonStreamingRunErrorRouteImport.update({
  id: '/api/non-streaming-run-error',
  path: '/api/non-streaming-run-error',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMultimodalToolResultWireRoute =
  ApiMultimodalToolResultWireRouteImport.update({
    id: '/api/multimodal-tool-result-wire',
    path: '/api/multimodal-tool-result-wire',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMistralStrictToolNullWireRoute =
  ApiMistralStrictToolNullWireRouteImport.update({
    id: '/api/mistral-strict-tool-null-wire',
    path: '/api/mistral-strict-tool-null-wire',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMiddlewareTestRoute = ApiMiddlewareTestRouteImport.update({
  id: '/api/middleware-test',
  path: '/api/middleware-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessageIdsRoute = ApiMessageIdsRouteImport.update({
  id: '/api/message-ids',
  path: '/api/message-ids',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpTestRoute = ApiMcpTestRouteImport.update({
  id: '/api/mcp-test',
  path: '/api/mcp-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpStatusTestRoute = ApiMcpStatusTestRouteImport.update({
  id: '/api/mcp-status-test',
  path: '/api/mcp-status-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpServerRoute = ApiMcpServerRouteImport.update({
  id: '/api/mcp-server',
  path: '/api/mcp-server',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpManagedTestRoute = ApiMcpManagedTestRouteImport.update({
  id: '/api/mcp-managed-test',
  path: '/api/mcp-managed-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpLifecycleTestRoute = ApiMcpLifecycleTestRouteImport.update({
  id: '/api/mcp-lifecycle-test',
  path: '/api/mcp-lifecycle-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpAppsServerRoute = ApiMcpAppsServerRouteImport.update({
  id: '/api/mcp-apps-server',
  path: '/api/mcp-apps-server',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpAppsChatRoute = ApiMcpAppsChatRouteImport.update({
  id: '/api/mcp-apps-chat',
  path: '/api/mcp-apps-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpAppsCallRoute = ApiMcpAppsCallRouteImport.update({
  id: '/api/mcp-apps-call',
  path: '/api/mcp-apps-call',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMaxToolCallsWireRoute = ApiMaxToolCallsWireRouteImport.update({
  id: '/api/max-tool-calls-wire',
  path: '/api/max-tool-calls-wire',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLazyToolsWireRoute = ApiLazyToolsWireRouteImport.update({
  id: '/api/lazy-tools-wire',
  path: '/api/lazy-tools-wire',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJoinRunClientToolRoute = ApiJoinRunClientToolRouteImport.update({
  id: '/api/join-run-client-tool',
  path: '/api/join-run-client-tool',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInterruptsTestRoute = ApiInterruptsTestRouteImport.update({
  id: '/api/interrupts-test',
  path: '/api/interrupts-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageRoute = ApiImageRouteImport.update({
  id: '/api/image',
  path: '/api/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerationPersistenceServerRoute =
  ApiGenerationPersistenceServerRouteImport.update({
    id: '/api/generation-persistence-server',
    path: '/api/generation-persistence-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGenerationPersistenceResumeRoute =
  ApiGenerationPersistenceResumeRouteImport.update({
    id: '/api/generation-persistence-resume',
    path: '/api/generation-persistence-resume',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGeminiNativeImageWireRoute =
  ApiGeminiNativeImageWireRouteImport.update({
    id: '/api/gemini-native-image-wire',
    path: '/api/gemini-native-image-wire',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGeminiImageGaModelsRoute = ApiGeminiImageGaModelsRouteImport.update({
  id: '/api/gemini-image-ga-models',
  path: '/api/gemini-image-ga-models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiForeignInterruptRoute = ApiForeignInterruptRouteImport.update({
  id: '/api/foreign-interrupt',
  path: '/api/foreign-interrupt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmbeddingRoute = ApiEmbeddingRouteImport.update({
  id: '/api/embedding',
  path: '/api/embedding',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDurableTakeoverRoute = ApiDurableTakeoverRouteImport.update({
  id: '/api/durable-takeover',
  path: '/api/durable-takeover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDurableDeliveryRoute = ApiDurableDeliveryRouteImport.update({
  id: '/api/durable-delivery',
  path: '/api/durable-delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevtoolsMemoryRoute = ApiDevtoolsMemoryRouteImport.update({
  id: '/api/devtools-memory',
  path: '/api/devtools-memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiByokChatRoute = ApiByokChatRouteImport.update({
  id: '/api/byok-chat',
  path: '/api/byok-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiByteplusSeedance1080pWireRoute =
  ApiByteplusSeedance1080pWireRouteImport.update({
    id: '/api/byteplus-seedance-1080p-wire',
    path: '/api/byteplus-seedance-1080p-wire',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAudioRoute = ApiAudioRouteImport.update({
  id: '/api/audio',
  path: '/api/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArktypeToolWireRoute = ApiArktypeToolWireRouteImport.update({
  id: '/api/arktype-tool-wire',
  path: '/api/arktype-tool-wire',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnthropicStructuredUsageRoute =
  ApiAnthropicStructuredUsageRouteImport.update({
    id: '/api/anthropic-structured-usage',
    path: '/api/anthropic-structured-usage',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAnthropicSkillsWireRoute = ApiAnthropicSkillsWireRouteImport.update({
  id: '/api/anthropic-skills-wire',
  path: '/api/anthropic-skills-wire',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnthropicBugTestRoute = ApiAnthropicBugTestRouteImport.update({
  id: '/api/anthropic-bug-test',
  path: '/api/anthropic-bug-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderFeatureRoute = ProviderFeatureRouteImport.update({
  id: '/$provider/$feature',
  path: '/$provider/$feature',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoStreamRoute = ApiVideoStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiVideoRoute,
} as any)
const ApiTtsStreamRoute = ApiTtsStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiTtsRoute,
} as any)
const ApiTranscriptionStreamRoute = ApiTranscriptionStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiTranscriptionRoute,
} as any)
const ApiImageStreamRoute = ApiImageStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiImageRoute,
} as any)
const ApiAudioStreamRoute = ApiAudioStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiAudioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/byok': typeof ByokRoute
  '/chat-client-default-bridge': typeof ChatClientDefaultBridgeRoute
  '/devtools-chat': typeof DevtoolsChatRoute
  '/devtools-generation-hooks': typeof DevtoolsGenerationHooksRoute
  '/devtools-memory': typeof DevtoolsMemoryRoute
  '/devtools-route-a': typeof DevtoolsRouteARoute
  '/devtools-route-b': typeof DevtoolsRouteBRoute
  '/devtools-structured': typeof DevtoolsStructuredRoute
  '/devtools-tools': typeof DevtoolsToolsRoute
  '/foreign-interrupt': typeof ForeignInterruptRoute
  '/generation-persistence-resume': typeof GenerationPersistenceResumeRoute
  '/generation-persistence-server': typeof GenerationPersistenceServerRoute
  '/interrupts-test': typeof InterruptsTestRoute
  '/join-run-client-tool': typeof JoinRunClientToolRoute
  '/markdown-cjk': typeof MarkdownCjkRoute
  '/middleware-test': typeof MiddlewareTestRoute
  '/persistence-durability': typeof PersistenceDurabilityRoute
  '/tools-test': typeof ToolsTestRoute
  '/websocket-adapter': typeof WebsocketAdapterRoute
  '/$provider/$feature': typeof ProviderFeatureRoute
  '/api/anthropic-bug-test': typeof ApiAnthropicBugTestRoute
  '/api/anthropic-skills-wire': typeof ApiAnthropicSkillsWireRoute
  '/api/anthropic-structured-usage': typeof ApiAnthropicStructuredUsageRoute
  '/api/arktype-tool-wire': typeof ApiArktypeToolWireRoute
  '/api/audio': typeof ApiAudioRouteWithChildren
  '/api/byok-chat': typeof ApiByokChatRoute
  '/api/byteplus-seedance-1080p-wire': typeof ApiByteplusSeedance1080pWireRoute
  '/api/chat': typeof ApiChatRoute
  '/api/devtools-memory': typeof ApiDevtoolsMemoryRoute
  '/api/durable-delivery': typeof ApiDurableDeliveryRoute
  '/api/durable-takeover': typeof ApiDurableTakeoverRoute
  '/api/embedding': typeof ApiEmbeddingRoute
  '/api/foreign-interrupt': typeof ApiForeignInterruptRoute
  '/api/gemini-image-ga-models': typeof ApiGeminiImageGaModelsRoute
  '/api/gemini-native-image-wire': typeof ApiGeminiNativeImageWireRoute
  '/api/generation-persistence-resume': typeof ApiGenerationPersistenceResumeRoute
  '/api/generation-persistence-server': typeof ApiGenerationPersistenceServerRoute
  '/api/image': typeof ApiImageRouteWithChildren
  '/api/interrupts-test': typeof ApiInterruptsTestRoute
  '/api/join-run-client-tool': typeof ApiJoinRunClientToolRoute
  '/api/lazy-tools-wire': typeof ApiLazyToolsWireRoute
  '/api/max-tool-calls-wire': typeof ApiMaxToolCallsWireRoute
  '/api/mcp-apps-call': typeof ApiMcpAppsCallRoute
  '/api/mcp-apps-chat': typeof ApiMcpAppsChatRoute
  '/api/mcp-apps-server': typeof ApiMcpAppsServerRoute
  '/api/mcp-lifecycle-test': typeof ApiMcpLifecycleTestRoute
  '/api/mcp-managed-test': typeof ApiMcpManagedTestRoute
  '/api/mcp-server': typeof ApiMcpServerRoute
  '/api/mcp-status-test': typeof ApiMcpStatusTestRoute
  '/api/mcp-test': typeof ApiMcpTestRoute
  '/api/message-ids': typeof ApiMessageIdsRoute
  '/api/middleware-test': typeof ApiMiddlewareTestRoute
  '/api/mistral-strict-tool-null-wire': typeof ApiMistralStrictToolNullWireRoute
  '/api/multimodal-tool-result-wire': typeof ApiMultimodalToolResultWireRoute
  '/api/non-streaming-run-error': typeof ApiNonStreamingRunErrorRoute
  '/api/openai-completed-response-text': typeof ApiOpenaiCompletedResponseTextRoute
  '/api/openai-shell-skills-wire': typeof ApiOpenaiShellSkillsWireRoute
  '/api/openai-strict-tool-null-wire': typeof ApiOpenaiStrictToolNullWireRoute
  '/api/openai-usage-details': typeof ApiOpenaiUsageDetailsRoute
  '/api/openrouter-cost': typeof ApiOpenrouterCostRoute
  '/api/openrouter-json-object-wire': typeof ApiOpenrouterJsonObjectWireRoute
  '/api/openrouter-reasoning-wire': typeof ApiOpenrouterReasoningWireRoute
  '/api/openrouter-web-tools-wire': typeof ApiOpenrouterWebToolsWireRoute
  '/api/otel-media': typeof ApiOtelMediaRoute
  '/api/otel-transcription': typeof ApiOtelTranscriptionRoute
  '/api/otel-usage': typeof ApiOtelUsageRoute
  '/api/persistence-durability': typeof ApiPersistenceDurabilityRoute
  '/api/provider-tool-dispatch-wire': typeof ApiProviderToolDispatchWireRoute
  '/api/sandbox-durability': typeof ApiSandboxDurabilityRoute
  '/api/sandbox-file-persistence': typeof ApiSandboxFilePersistenceRoute
  '/api/sandbox-tool-history': typeof ApiSandboxToolHistoryRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/api/tool-call-lifecycle-wire': typeof ApiToolCallLifecycleWireRoute
  '/api/tools-test': typeof ApiToolsTestRoute
  '/api/transcription': typeof ApiTranscriptionRouteWithChildren
  '/api/tts': typeof ApiTtsRouteWithChildren
  '/api/video': typeof ApiVideoRouteWithChildren
  '/$provider/': typeof ProviderIndexRoute
  '/api/audio/stream': typeof ApiAudioStreamRoute
  '/api/image/stream': typeof ApiImageStreamRoute
  '/api/transcription/stream': typeof ApiTranscriptionStreamRoute
  '/api/tts/stream': typeof ApiTtsStreamRoute
  '/api/video/stream': typeof ApiVideoStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/byok': typeof ByokRoute
  '/chat-client-default-bridge': typeof ChatClientDefaultBridgeRoute
  '/devtools-chat': typeof DevtoolsChatRoute
  '/devtools-generation-hooks': typeof DevtoolsGenerationHooksRoute
  '/devtools-memory': typeof DevtoolsMemoryRoute
  '/devtools-route-a': typeof DevtoolsRouteARoute
  '/devtools-route-b': typeof DevtoolsRouteBRoute
  '/devtools-structured': typeof DevtoolsStructuredRoute
  '/devtools-tools': typeof DevtoolsToolsRoute
  '/foreign-interrupt': typeof ForeignInterruptRoute
  '/generation-persistence-resume': typeof GenerationPersistenceResumeRoute
  '/generation-persistence-server': typeof GenerationPersistenceServerRoute
  '/interrupts-test': typeof InterruptsTestRoute
  '/join-run-client-tool': typeof JoinRunClientToolRoute
  '/markdown-cjk': typeof MarkdownCjkRoute
  '/middleware-test': typeof MiddlewareTestRoute
  '/persistence-durability': typeof PersistenceDurabilityRoute
  '/tools-test': typeof ToolsTestRoute
  '/websocket-adapter': typeof WebsocketAdapterRoute
  '/$provider/$feature': typeof ProviderFeatureRoute
  '/api/anthropic-bug-test': typeof ApiAnthropicBugTestRoute
  '/api/anthropic-skills-wire': typeof ApiAnthropicSkillsWireRoute
  '/api/anthropic-structured-usage': typeof ApiAnthropicStructuredUsageRoute
  '/api/arktype-tool-wire': typeof ApiArktypeToolWireRoute
  '/api/audio': typeof ApiAudioRouteWithChildren
  '/api/byok-chat': typeof ApiByokChatRoute
  '/api/byteplus-seedance-1080p-wire': typeof ApiByteplusSeedance1080pWireRoute
  '/api/chat': typeof ApiChatRoute
  '/api/devtools-memory': typeof ApiDevtoolsMemoryRoute
  '/api/durable-delivery': typeof ApiDurableDeliveryRoute
  '/api/durable-takeover': typeof ApiDurableTakeoverRoute
  '/api/embedding': typeof ApiEmbeddingRoute
  '/api/foreign-interrupt': typeof ApiForeignInterruptRoute
  '/api/gemini-image-ga-models': typeof ApiGeminiImageGaModelsRoute
  '/api/gemini-native-image-wire': typeof ApiGeminiNativeImageWireRoute
  '/api/generation-persistence-resume': typeof ApiGenerationPersistenceResumeRoute
  '/api/generation-persistence-server': typeof ApiGenerationPersistenceServerRoute
  '/api/image': typeof ApiImageRouteWithChildren
  '/api/interrupts-test': typeof ApiInterruptsTestRoute
  '/api/join-run-client-tool': typeof ApiJoinRunClientToolRoute
  '/api/lazy-tools-wire': typeof ApiLazyToolsWireRoute
  '/api/max-tool-calls-wire': typeof ApiMaxToolCallsWireRoute
  '/api/mcp-apps-call': typeof ApiMcpAppsCallRoute
  '/api/mcp-apps-chat': typeof ApiMcpAppsChatRoute
  '/api/mcp-apps-server': typeof ApiMcpAppsServerRoute
  '/api/mcp-lifecycle-test': typeof ApiMcpLifecycleTestRoute
  '/api/mcp-managed-test': typeof ApiMcpManagedTestRoute
  '/api/mcp-server': typeof ApiMcpServerRoute
  '/api/mcp-status-test': typeof ApiMcpStatusTestRoute
  '/api/mcp-test': typeof ApiMcpTestRoute
  '/api/message-ids': typeof ApiMessageIdsRoute
  '/api/middleware-test': typeof ApiMiddlewareTestRoute
  '/api/mistral-strict-tool-null-wire': typeof ApiMistralStrictToolNullWireRoute
  '/api/multimodal-tool-result-wire': typeof ApiMultimodalToolResultWireRoute
  '/api/non-streaming-run-error': typeof ApiNonStreamingRunErrorRoute
  '/api/openai-completed-response-text': typeof ApiOpenaiCompletedResponseTextRoute
  '/api/openai-shell-skills-wire': typeof ApiOpenaiShellSkillsWireRoute
  '/api/openai-strict-tool-null-wire': typeof ApiOpenaiStrictToolNullWireRoute
  '/api/openai-usage-details': typeof ApiOpenaiUsageDetailsRoute
  '/api/openrouter-cost': typeof ApiOpenrouterCostRoute
  '/api/openrouter-json-object-wire': typeof ApiOpenrouterJsonObjectWireRoute
  '/api/openrouter-reasoning-wire': typeof ApiOpenrouterReasoningWireRoute
  '/api/openrouter-web-tools-wire': typeof ApiOpenrouterWebToolsWireRoute
  '/api/otel-media': typeof ApiOtelMediaRoute
  '/api/otel-transcription': typeof ApiOtelTranscriptionRoute
  '/api/otel-usage': typeof ApiOtelUsageRoute
  '/api/persistence-durability': typeof ApiPersistenceDurabilityRoute
  '/api/provider-tool-dispatch-wire': typeof ApiProviderToolDispatchWireRoute
  '/api/sandbox-durability': typeof ApiSandboxDurabilityRoute
  '/api/sandbox-file-persistence': typeof ApiSandboxFilePersistenceRoute
  '/api/sandbox-tool-history': typeof ApiSandboxToolHistoryRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/api/tool-call-lifecycle-wire': typeof ApiToolCallLifecycleWireRoute
  '/api/tools-test': typeof ApiToolsTestRoute
  '/api/transcription': typeof ApiTranscriptionRouteWithChildren
  '/api/tts': typeof ApiTtsRouteWithChildren
  '/api/video': typeof ApiVideoRouteWithChildren
  '/$provider': typeof ProviderIndexRoute
  '/api/audio/stream': typeof ApiAudioStreamRoute
  '/api/image/stream': typeof ApiImageStreamRoute
  '/api/transcription/stream': typeof ApiTranscriptionStreamRoute
  '/api/tts/stream': typeof ApiTtsStreamRoute
  '/api/video/stream': typeof ApiVideoStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/byok': typeof ByokRoute
  '/chat-client-default-bridge': typeof ChatClientDefaultBridgeRoute
  '/devtools-chat': typeof DevtoolsChatRoute
  '/devtools-generation-hooks': typeof DevtoolsGenerationHooksRoute
  '/devtools-memory': typeof DevtoolsMemoryRoute
  '/devtools-route-a': typeof DevtoolsRouteARoute
  '/devtools-route-b': typeof DevtoolsRouteBRoute
  '/devtools-structured': typeof DevtoolsStructuredRoute
  '/devtools-tools': typeof DevtoolsToolsRoute
  '/foreign-interrupt': typeof ForeignInterruptRoute
  '/generation-persistence-resume': typeof GenerationPersistenceResumeRoute
  '/generation-persistence-server': typeof GenerationPersistenceServerRoute
  '/interrupts-test': typeof InterruptsTestRoute
  '/join-run-client-tool': typeof JoinRunClientToolRoute
  '/markdown-cjk': typeof MarkdownCjkRoute
  '/middleware-test': typeof MiddlewareTestRoute
  '/persistence-durability': typeof PersistenceDurabilityRoute
  '/tools-test': typeof ToolsTestRoute
  '/websocket-adapter': typeof WebsocketAdapterRoute
  '/$provider/$feature': typeof ProviderFeatureRoute
  '/api/anthropic-bug-test': typeof ApiAnthropicBugTestRoute
  '/api/anthropic-skills-wire': typeof ApiAnthropicSkillsWireRoute
  '/api/anthropic-structured-usage': typeof ApiAnthropicStructuredUsageRoute
  '/api/arktype-tool-wire': typeof ApiArktypeToolWireRoute
  '/api/audio': typeof ApiAudioRouteWithChildren
  '/api/byok-chat': typeof ApiByokChatRoute
  '/api/byteplus-seedance-1080p-wire': typeof ApiByteplusSeedance1080pWireRoute
  '/api/chat': typeof ApiChatRoute
  '/api/devtools-memory': typeof ApiDevtoolsMemoryRoute
  '/api/durable-delivery': typeof ApiDurableDeliveryRoute
  '/api/durable-takeover': typeof ApiDurableTakeoverRoute
  '/api/embedding': typeof ApiEmbeddingRoute
  '/api/foreign-interrupt': typeof ApiForeignInterruptRoute
  '/api/gemini-image-ga-models': typeof ApiGeminiImageGaModelsRoute
  '/api/gemini-native-image-wire': typeof ApiGeminiNativeImageWireRoute
  '/api/generation-persistence-resume': typeof ApiGenerationPersistenceResumeRoute
  '/api/generation-persistence-server': typeof ApiGenerationPersistenceServerRoute
  '/api/image': typeof ApiImageRouteWithChildren
  '/api/interrupts-test': typeof ApiInterruptsTestRoute
  '/api/join-run-client-tool': typeof ApiJoinRunClientToolRoute
  '/api/lazy-tools-wire': typeof ApiLazyToolsWireRoute
  '/api/max-tool-calls-wire': typeof ApiMaxToolCallsWireRoute
  '/api/mcp-apps-call': typeof ApiMcpAppsCallRoute
  '/api/mcp-apps-chat': typeof ApiMcpAppsChatRoute
  '/api/mcp-apps-server': typeof ApiMcpAppsServerRoute
  '/api/mcp-lifecycle-test': typeof ApiMcpLifecycleTestRoute
  '/api/mcp-managed-test': typeof ApiMcpManagedTestRoute
  '/api/mcp-server': typeof ApiMcpServerRoute
  '/api/mcp-status-test': typeof ApiMcpStatusTestRoute
  '/api/mcp-test': typeof ApiMcpTestRoute
  '/api/message-ids': typeof ApiMessageIdsRoute
  '/api/middleware-test': typeof ApiMiddlewareTestRoute
  '/api/mistral-strict-tool-null-wire': typeof ApiMistralStrictToolNullWireRoute
  '/api/multimodal-tool-result-wire': typeof ApiMultimodalToolResultWireRoute
  '/api/non-streaming-run-error': typeof ApiNonStreamingRunErrorRoute
  '/api/openai-completed-response-text': typeof ApiOpenaiCompletedResponseTextRoute
  '/api/openai-shell-skills-wire': typeof ApiOpenaiShellSkillsWireRoute
  '/api/openai-strict-tool-null-wire': typeof ApiOpenaiStrictToolNullWireRoute
  '/api/openai-usage-details': typeof ApiOpenaiUsageDetailsRoute
  '/api/openrouter-cost': typeof ApiOpenrouterCostRoute
  '/api/openrouter-json-object-wire': typeof ApiOpenrouterJsonObjectWireRoute
  '/api/openrouter-reasoning-wire': typeof ApiOpenrouterReasoningWireRoute
  '/api/openrouter-web-tools-wire': typeof ApiOpenrouterWebToolsWireRoute
  '/api/otel-media': typeof ApiOtelMediaRoute
  '/api/otel-transcription': typeof ApiOtelTranscriptionRoute
  '/api/otel-usage': typeof ApiOtelUsageRoute
  '/api/persistence-durability': typeof ApiPersistenceDurabilityRoute
  '/api/provider-tool-dispatch-wire': typeof ApiProviderToolDispatchWireRoute
  '/api/sandbox-durability': typeof ApiSandboxDurabilityRoute
  '/api/sandbox-file-persistence': typeof ApiSandboxFilePersistenceRoute
  '/api/sandbox-tool-history': typeof ApiSandboxToolHistoryRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/api/tool-call-lifecycle-wire': typeof ApiToolCallLifecycleWireRoute
  '/api/tools-test': typeof ApiToolsTestRoute
  '/api/transcription': typeof ApiTranscriptionRouteWithChildren
  '/api/tts': typeof ApiTtsRouteWithChildren
  '/api/video': typeof ApiVideoRouteWithChildren
  '/$provider/': typeof ProviderIndexRoute
  '/api/audio/stream': typeof ApiAudioStreamRoute
  '/api/image/stream': typeof ApiImageStreamRoute
  '/api/transcription/stream': typeof ApiTranscriptionStreamRoute
  '/api/tts/stream': typeof ApiTtsStreamRoute
  '/api/video/stream': typeof ApiVideoStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/byok'
    | '/chat-client-default-bridge'
    | '/devtools-chat'
    | '/devtools-generation-hooks'
    | '/devtools-memory'
    | '/devtools-route-a'
    | '/devtools-route-b'
    | '/devtools-structured'
    | '/devtools-tools'
    | '/foreign-interrupt'
    | '/generation-persistence-resume'
    | '/generation-persistence-server'
    | '/interrupts-test'
    | '/join-run-client-tool'
    | '/markdown-cjk'
    | '/middleware-test'
    | '/persistence-durability'
    | '/tools-test'
    | '/websocket-adapter'
    | '/$provider/$feature'
    | '/api/anthropic-bug-test'
    | '/api/anthropic-skills-wire'
    | '/api/anthropic-structured-usage'
    | '/api/arktype-tool-wire'
    | '/api/audio'
    | '/api/byok-chat'
    | '/api/byteplus-seedance-1080p-wire'
    | '/api/chat'
    | '/api/devtools-memory'
    | '/api/durable-delivery'
    | '/api/durable-takeover'
    | '/api/embedding'
    | '/api/foreign-interrupt'
    | '/api/gemini-image-ga-models'
    | '/api/gemini-native-image-wire'
    | '/api/generation-persistence-resume'
    | '/api/generation-persistence-server'
    | '/api/image'
    | '/api/interrupts-test'
    | '/api/join-run-client-tool'
    | '/api/lazy-tools-wire'
    | '/api/max-tool-calls-wire'
    | '/api/mcp-apps-call'
    | '/api/mcp-apps-chat'
    | '/api/mcp-apps-server'
    | '/api/mcp-lifecycle-test'
    | '/api/mcp-managed-test'
    | '/api/mcp-server'
    | '/api/mcp-status-test'
    | '/api/mcp-test'
    | '/api/message-ids'
    | '/api/middleware-test'
    | '/api/mistral-strict-tool-null-wire'
    | '/api/multimodal-tool-result-wire'
    | '/api/non-streaming-run-error'
    | '/api/openai-completed-response-text'
    | '/api/openai-shell-skills-wire'
    | '/api/openai-strict-tool-null-wire'
    | '/api/openai-usage-details'
    | '/api/openrouter-cost'
    | '/api/openrouter-json-object-wire'
    | '/api/openrouter-reasoning-wire'
    | '/api/openrouter-web-tools-wire'
    | '/api/otel-media'
    | '/api/otel-transcription'
    | '/api/otel-usage'
    | '/api/persistence-durability'
    | '/api/provider-tool-dispatch-wire'
    | '/api/sandbox-durability'
    | '/api/sandbox-file-persistence'
    | '/api/sandbox-tool-history'
    | '/api/summarize'
    | '/api/tool-call-lifecycle-wire'
    | '/api/tools-test'
    | '/api/transcription'
    | '/api/tts'
    | '/api/video'
    | '/$provider/'
    | '/api/audio/stream'
    | '/api/image/stream'
    | '/api/transcription/stream'
    | '/api/tts/stream'
    | '/api/video/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/byok'
    | '/chat-client-default-bridge'
    | '/devtools-chat'
    | '/devtools-generation-hooks'
    | '/devtools-memory'
    | '/devtools-route-a'
    | '/devtools-route-b'
    | '/devtools-structured'
    | '/devtools-tools'
    | '/foreign-interrupt'
    | '/generation-persistence-resume'
    | '/generation-persistence-server'
    | '/interrupts-test'
    | '/join-run-client-tool'
    | '/markdown-cjk'
    | '/middleware-test'
    | '/persistence-durability'
    | '/tools-test'
    | '/websocket-adapter'
    | '/$provider/$feature'
    | '/api/anthropic-bug-test'
    | '/api/anthropic-skills-wire'
    | '/api/anthropic-structured-usage'
    | '/api/arktype-tool-wire'
    | '/api/audio'
    | '/api/byok-chat'
    | '/api/byteplus-seedance-1080p-wire'
    | '/api/chat'
    | '/api/devtools-memory'
    | '/api/durable-delivery'
    | '/api/durable-takeover'
    | '/api/embedding'
    | '/api/foreign-interrupt'
    | '/api/gemini-image-ga-models'
    | '/api/gemini-native-image-wire'
    | '/api/generation-persistence-resume'
    | '/api/generation-persistence-server'
    | '/api/image'
    | '/api/interrupts-test'
    | '/api/join-run-client-tool'
    | '/api/lazy-tools-wire'
    | '/api/max-tool-calls-wire'
    | '/api/mcp-apps-call'
    | '/api/mcp-apps-chat'
    | '/api/mcp-apps-server'
    | '/api/mcp-lifecycle-test'
    | '/api/mcp-managed-test'
    | '/api/mcp-server'
    | '/api/mcp-status-test'
    | '/api/mcp-test'
    | '/api/message-ids'
    | '/api/middleware-test'
    | '/api/mistral-strict-tool-null-wire'
    | '/api/multimodal-tool-result-wire'
    | '/api/non-streaming-run-error'
    | '/api/openai-completed-response-text'
    | '/api/openai-shell-skills-wire'
    | '/api/openai-strict-tool-null-wire'
    | '/api/openai-usage-details'
    | '/api/openrouter-cost'
    | '/api/openrouter-json-object-wire'
    | '/api/openrouter-reasoning-wire'
    | '/api/openrouter-web-tools-wire'
    | '/api/otel-media'
    | '/api/otel-transcription'
    | '/api/otel-usage'
    | '/api/persistence-durability'
    | '/api/provider-tool-dispatch-wire'
    | '/api/sandbox-durability'
    | '/api/sandbox-file-persistence'
    | '/api/sandbox-tool-history'
    | '/api/summarize'
    | '/api/tool-call-lifecycle-wire'
    | '/api/tools-test'
    | '/api/transcription'
    | '/api/tts'
    | '/api/video'
    | '/$provider'
    | '/api/audio/stream'
    | '/api/image/stream'
    | '/api/transcription/stream'
    | '/api/tts/stream'
    | '/api/video/stream'
  id:
    | '__root__'
    | '/'
    | '/byok'
    | '/chat-client-default-bridge'
    | '/devtools-chat'
    | '/devtools-generation-hooks'
    | '/devtools-memory'
    | '/devtools-route-a'
    | '/devtools-route-b'
    | '/devtools-structured'
    | '/devtools-tools'
    | '/foreign-interrupt'
    | '/generation-persistence-resume'
    | '/generation-persistence-server'
    | '/interrupts-test'
    | '/join-run-client-tool'
    | '/markdown-cjk'
    | '/middleware-test'
    | '/persistence-durability'
    | '/tools-test'
    | '/websocket-adapter'
    | '/$provider/$feature'
    | '/api/anthropic-bug-test'
    | '/api/anthropic-skills-wire'
    | '/api/anthropic-structured-usage'
    | '/api/arktype-tool-wire'
    | '/api/audio'
    | '/api/byok-chat'
    | '/api/byteplus-seedance-1080p-wire'
    | '/api/chat'
    | '/api/devtools-memory'
    | '/api/durable-delivery'
    | '/api/durable-takeover'
    | '/api/embedding'
    | '/api/foreign-interrupt'
    | '/api/gemini-image-ga-models'
    | '/api/gemini-native-image-wire'
    | '/api/generation-persistence-resume'
    | '/api/generation-persistence-server'
    | '/api/image'
    | '/api/interrupts-test'
    | '/api/join-run-client-tool'
    | '/api/lazy-tools-wire'
    | '/api/max-tool-calls-wire'
    | '/api/mcp-apps-call'
    | '/api/mcp-apps-chat'
    | '/api/mcp-apps-server'
    | '/api/mcp-lifecycle-test'
    | '/api/mcp-managed-test'
    | '/api/mcp-server'
    | '/api/mcp-status-test'
    | '/api/mcp-test'
    | '/api/message-ids'
    | '/api/middleware-test'
    | '/api/mistral-strict-tool-null-wire'
    | '/api/multimodal-tool-result-wire'
    | '/api/non-streaming-run-error'
    | '/api/openai-completed-response-text'
    | '/api/openai-shell-skills-wire'
    | '/api/openai-strict-tool-null-wire'
    | '/api/openai-usage-details'
    | '/api/openrouter-cost'
    | '/api/openrouter-json-object-wire'
    | '/api/openrouter-reasoning-wire'
    | '/api/openrouter-web-tools-wire'
    | '/api/otel-media'
    | '/api/otel-transcription'
    | '/api/otel-usage'
    | '/api/persistence-durability'
    | '/api/provider-tool-dispatch-wire'
    | '/api/sandbox-durability'
    | '/api/sandbox-file-persistence'
    | '/api/sandbox-tool-history'
    | '/api/summarize'
    | '/api/tool-call-lifecycle-wire'
    | '/api/tools-test'
    | '/api/transcription'
    | '/api/tts'
    | '/api/video'
    | '/$provider/'
    | '/api/audio/stream'
    | '/api/image/stream'
    | '/api/transcription/stream'
    | '/api/tts/stream'
    | '/api/video/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ByokRoute: typeof ByokRoute
  ChatClientDefaultBridgeRoute: typeof ChatClientDefaultBridgeRoute
  DevtoolsChatRoute: typeof DevtoolsChatRoute
  DevtoolsGenerationHooksRoute: typeof DevtoolsGenerationHooksRoute
  DevtoolsMemoryRoute: typeof DevtoolsMemoryRoute
  DevtoolsRouteARoute: typeof DevtoolsRouteARoute
  DevtoolsRouteBRoute: typeof DevtoolsRouteBRoute
  DevtoolsStructuredRoute: typeof DevtoolsStructuredRoute
  DevtoolsToolsRoute: typeof DevtoolsToolsRoute
  ForeignInterruptRoute: typeof ForeignInterruptRoute
  GenerationPersistenceResumeRoute: typeof GenerationPersistenceResumeRoute
  GenerationPersistenceServerRoute: typeof GenerationPersistenceServerRoute
  InterruptsTestRoute: typeof InterruptsTestRoute
  JoinRunClientToolRoute: typeof JoinRunClientToolRoute
  MarkdownCjkRoute: typeof MarkdownCjkRoute
  MiddlewareTestRoute: typeof MiddlewareTestRoute
  PersistenceDurabilityRoute: typeof PersistenceDurabilityRoute
  ToolsTestRoute: typeof ToolsTestRoute
  WebsocketAdapterRoute: typeof WebsocketAdapterRoute
  ProviderFeatureRoute: typeof ProviderFeatureRoute
  ApiAnthropicBugTestRoute: typeof ApiAnthropicBugTestRoute
  ApiAnthropicSkillsWireRoute: typeof ApiAnthropicSkillsWireRoute
  ApiAnthropicStructuredUsageRoute: typeof ApiAnthropicStructuredUsageRoute
  ApiArktypeToolWireRoute: typeof ApiArktypeToolWireRoute
  ApiAudioRoute: typeof ApiAudioRouteWithChildren
  ApiByokChatRoute: typeof ApiByokChatRoute
  ApiByteplusSeedance1080pWireRoute: typeof ApiByteplusSeedance1080pWireRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDevtoolsMemoryRoute: typeof ApiDevtoolsMemoryRoute
  ApiDurableDeliveryRoute: typeof ApiDurableDeliveryRoute
  ApiDurableTakeoverRoute: typeof ApiDurableTakeoverRoute
  ApiEmbeddingRoute: typeof ApiEmbeddingRoute
  ApiForeignInterruptRoute: typeof ApiForeignInterruptRoute
  ApiGeminiImageGaModelsRoute: typeof ApiGeminiImageGaModelsRoute
  ApiGeminiNativeImageWireRoute: typeof ApiGeminiNativeImageWireRoute
  ApiGenerationPersistenceResumeRoute: typeof ApiGenerationPersistenceResumeRoute
  ApiGenerationPersistenceServerRoute: typeof ApiGenerationPersistenceServerRoute
  ApiImageRoute: typeof ApiImageRouteWithChildren
  ApiInterruptsTestRoute: typeof ApiInterruptsTestRoute
  ApiJoinRunClientToolRoute: typeof ApiJoinRunClientToolRoute
  ApiLazyToolsWireRoute: typeof ApiLazyToolsWireRoute
  ApiMaxToolCallsWireRoute: typeof ApiMaxToolCallsWireRoute
  ApiMcpAppsCallRoute: typeof ApiMcpAppsCallRoute
  ApiMcpAppsChatRoute: typeof ApiMcpAppsChatRoute
  ApiMcpAppsServerRoute: typeof ApiMcpAppsServerRoute
  ApiMcpLifecycleTestRoute: typeof ApiMcpLifecycleTestRoute
  ApiMcpManagedTestRoute: typeof ApiMcpManagedTestRoute
  ApiMcpServerRoute: typeof ApiMcpServerRoute
  ApiMcpStatusTestRoute: typeof ApiMcpStatusTestRoute
  ApiMcpTestRoute: typeof ApiMcpTestRoute
  ApiMessageIdsRoute: typeof ApiMessageIdsRoute
  ApiMiddlewareTestRoute: typeof ApiMiddlewareTestRoute
  ApiMistralStrictToolNullWireRoute: typeof ApiMistralStrictToolNullWireRoute
  ApiMultimodalToolResultWireRoute: typeof ApiMultimodalToolResultWireRoute
  ApiNonStreamingRunErrorRoute: typeof ApiNonStreamingRunErrorRoute
  ApiOpenaiCompletedResponseTextRoute: typeof ApiOpenaiCompletedResponseTextRoute
  ApiOpenaiShellSkillsWireRoute: typeof ApiOpenaiShellSkillsWireRoute
  ApiOpenaiStrictToolNullWireRoute: typeof ApiOpenaiStrictToolNullWireRoute
  ApiOpenaiUsageDetailsRoute: typeof ApiOpenaiUsageDetailsRoute
  ApiOpenrouterCostRoute: typeof ApiOpenrouterCostRoute
  ApiOpenrouterJsonObjectWireRoute: typeof ApiOpenrouterJsonObjectWireRoute
  ApiOpenrouterReasoningWireRoute: typeof ApiOpenrouterReasoningWireRoute
  ApiOpenrouterWebToolsWireRoute: typeof ApiOpenrouterWebToolsWireRoute
  ApiOtelMediaRoute: typeof ApiOtelMediaRoute
  ApiOtelTranscriptionRoute: typeof ApiOtelTranscriptionRoute
  ApiOtelUsageRoute: typeof ApiOtelUsageRoute
  ApiPersistenceDurabilityRoute: typeof ApiPersistenceDurabilityRoute
  ApiProviderToolDispatchWireRoute: typeof ApiProviderToolDispatchWireRoute
  ApiSandboxDurabilityRoute: typeof ApiSandboxDurabilityRoute
  ApiSandboxFilePersistenceRoute: typeof ApiSandboxFilePersistenceRoute
  ApiSandboxToolHistoryRoute: typeof ApiSandboxToolHistoryRoute
  ApiSummarizeRoute: typeof ApiSummarizeRoute
  ApiToolCallLifecycleWireRoute: typeof ApiToolCallLifecycleWireRoute
  ApiToolsTestRoute: typeof ApiToolsTestRoute
  ApiTranscriptionRoute: typeof ApiTranscriptionRouteWithChildren
  ApiTtsRoute: typeof ApiTtsRouteWithChildren
  ApiVideoRoute: typeof ApiVideoRouteWithChildren
  ProviderIndexRoute: typeof ProviderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/websocket-adapter': {
      id: '/websocket-adapter'
      path: '/websocket-adapter'
      fullPath: '/websocket-adapter'
      preLoaderRoute: typeof WebsocketAdapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools-test': {
      id: '/tools-test'
      path: '/tools-test'
      fullPath: '/tools-test'
      preLoaderRoute: typeof ToolsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persistence-durability': {
      id: '/persistence-durability'
      path: '/persistence-durability'
      fullPath: '/persistence-durability'
      preLoaderRoute: typeof PersistenceDurabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/middleware-test': {
      id: '/middleware-test'
      path: '/middleware-test'
      fullPath: '/middleware-test'
      preLoaderRoute: typeof MiddlewareTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markdown-cjk': {
      id: '/markdown-cjk'
      path: '/markdown-cjk'
      fullPath: '/markdown-cjk'
      preLoaderRoute: typeof MarkdownCjkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-run-client-tool': {
      id: '/join-run-client-tool'
      path: '/join-run-client-tool'
      fullPath: '/join-run-client-tool'
      preLoaderRoute: typeof JoinRunClientToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interrupts-test': {
      id: '/interrupts-test'
      path: '/interrupts-test'
      fullPath: '/interrupts-test'
      preLoaderRoute: typeof InterruptsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generation-persistence-server': {
      id: '/generation-persistence-server'
      path: '/generation-persistence-server'
      fullPath: '/generation-persistence-server'
      preLoaderRoute: typeof GenerationPersistenceServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generation-persistence-resume': {
      id: '/generation-persistence-resume'
      path: '/generation-persistence-resume'
      fullPath: '/generation-persistence-resume'
      preLoaderRoute: typeof GenerationPersistenceResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foreign-interrupt': {
      id: '/foreign-interrupt'
      path: '/foreign-interrupt'
      fullPath: '/foreign-interrupt'
      preLoaderRoute: typeof ForeignInterruptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devtools-tools': {
      id: '/devtools-tools'
      path: '/devtools-tools'
      fullPath: '/devtools-tools'
      preLoaderRoute: typeof DevtoolsToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devtools-structured': {
      id: '/devtools-structured'
      path: '/devtools-structured'
      fullPath: '/devtools-structured'
      preLoaderRoute: typeof DevtoolsStructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devtools-route-b': {
      id: '/devtools-route-b'
      path: '/devtools-route-b'
      fullPath: '/devtools-route-b'
      preLoaderRoute: typeof DevtoolsRouteBRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devtools-route-a': {
      id: '/devtools-route-a'
      path: '/devtools-route-a'
      fullPath: '/devtools-route-a'
      preLoaderRoute: typeof DevtoolsRouteARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devtools-memory': {
      id: '/devtools-memory'
      path: '/devtools-memory'
      fullPath: '/devtools-memory'
      preLoaderRoute: typeof DevtoolsMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devtools-generation-hooks': {
      id: '/devtools-generation-hooks'
      path: '/devtools-generation-hooks'
      fullPath: '/devtools-generation-hooks'
      preLoaderRoute: typeof DevtoolsGenerationHooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devtools-chat': {
      id: '/devtools-chat'
      path: '/devtools-chat'
      fullPath: '/devtools-chat'
      preLoaderRoute: typeof DevtoolsChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-client-default-bridge': {
      id: '/chat-client-default-bridge'
      path: '/chat-client-default-bridge'
      fullPath: '/chat-client-default-bridge'
      preLoaderRoute: typeof ChatClientDefaultBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/byok': {
      id: '/byok'
      path: '/byok'
      fullPath: '/byok'
      preLoaderRoute: typeof ByokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$provider/': {
      id: '/$provider/'
      path: '/$provider'
      fullPath: '/$provider/'
      preLoaderRoute: typeof ProviderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video': {
      id: '/api/video'
      path: '/api/video'
      fullPath: '/api/video'
      preLoaderRoute: typeof ApiVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcription': {
      id: '/api/transcription'
      path: '/api/transcription'
      fullPath: '/api/transcription'
      preLoaderRoute: typeof ApiTranscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tools-test': {
      id: '/api/tools-test'
      path: '/api/tools-test'
      fullPath: '/api/tools-test'
      preLoaderRoute: typeof ApiToolsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tool-call-lifecycle-wire': {
      id: '/api/tool-call-lifecycle-wire'
      path: '/api/tool-call-lifecycle-wire'
      fullPath: '/api/tool-call-lifecycle-wire'
      preLoaderRoute: typeof ApiToolCallLifecycleWireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/summarize': {
      id: '/api/summarize'
      path: '/api/summarize'
      fullPath: '/api/summarize'
      preLoaderRoute: typeof ApiSummarizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sandbox-tool-history': {
      id: '/api/sandbox-tool-history'
      path: '/api/sandbox-tool-history'
      fullPath: '/api/sandbox-tool-history'
      preLoaderRoute: typeof ApiSandboxToolHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sandbox-file-persistence': {
      id: '/api/sandbox-file-persistence'
      path: '/api/sandbox-file-persistence'
      fullPath: '/api/sandbox-file-persistence'
      preLoaderRoute: typeof ApiSandboxFilePersistenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sandbox-durability': {
      id: '/api/sandbox-durability'
      path: '/api/sandbox-durability'
      fullPath: '/api/sandbox-durability'
      preLoaderRoute: typeof ApiSandboxDurabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/provider-tool-dispatch-wire': {
      id: '/api/provider-tool-dispatch-wire'
      path: '/api/provider-tool-dispatch-wire'
      fullPath: '/api/provider-tool-dispatch-wire'
      preLoaderRoute: typeof ApiProviderToolDispatchWireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/persistence-durability': {
      id: '/api/persistence-durability'
      path: '/api/persistence-durability'
      fullPath: '/api/persistence-durability'
      preLoaderRoute: typeof ApiPersistenceDurabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/otel-usage': {
      id: '/api/otel-usage'
      path: '/api/otel-usage'
      fullPath: '/api/otel-usage'
      preLoaderRoute: typeof ApiOtelUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/otel-transcription': {
      id: '/api/otel-transcription'
      path: '/api/otel-transcription'
      fullPath: '/api/otel-transcription'
      preLoaderRoute: typeof ApiOtelTranscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/otel-media': {
      id: '/api/otel-media'
      path: '/api/otel-media'
      fullPath: '/api/otel-media'
      preLoaderRoute: typeof ApiOtelMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openrouter-web-tools-wire': {
      id: '/api/openrouter-web-tools-wire'
      path: '/api/openrouter-web-tools-wire'
      fullPath: '/api/openrouter-web-tools-wire'
      preLoaderRoute: typeof ApiOpenrouterWebToolsWireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openrouter-reasoning-wire': {
      id: '/api/openrouter-reasoning-wire'
      path: '/api/openrouter-reasoning-wire'
      fullPath: '/api/openrouter-reasoning-wire'
      preLoaderRoute: typeof ApiOpenrouterReasoningWireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openrouter-json-object-wire': {
      id: '/api/openrouter-json-object-wire'
      path: '/api/openrouter-json-object-wire'
      fullPath: '/api/openrouter-json-object-wire'
      preLoaderRoute: typeof ApiOpenrouterJsonObjectWireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openrouter-cost': {
      id: '/api/openrouter-cost'
      path: '/api/openrouter-cost'
      fullPath: '/api/openrouter-cost'
      preLoaderRoute: typeof ApiOpenrouterCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openai-usage-details': {
      id: '/api/openai-usage-details'
      path: '/api/openai-usage-details'
      fullPath: '/api/openai-usage-details'
      preLoaderRoute: typeof ApiOpenaiUsageDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openai-strict-tool-null-wire': {
      id: '/api/openai-strict-tool-null-wire'
      path: '/api/openai-strict-tool-null-wire'
      fullPath: '/api/openai-strict-tool-null-wire'
      preLoaderRoute: typeof ApiOpenaiStrictToolNullWireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openai-shell-skills-wire': {
      id: '/api/openai-shell-skills-wire'
      path: '/api/openai-shell-skills-wire'
      fullPath: '/api/openai-shell-skills-wire'
      preLoaderRoute: typeof ApiOpenaiShellSkillsWireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openai-completed-response-text': {
      id: '/api/openai-completed-response-text'
      path: '/api/openai-completed-response-text'
      fullPath: '/api/openai-completed-response-text'
      preLoaderRoute: typeof ApiOpenaiCompletedResponseTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/non-streaming-run-error': {
      id: '/api/non-streaming-run-error'
      path: '/api/non-streaming-run-error'
      fullPath: '/api/non-streaming-run-error'
      preLoaderRoute: typeof ApiNonStreamingRunErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/multimodal-tool-result-wire': {
      id: '/api/multimodal-tool-result-wire'
      path: '/api/multimodal-tool-result-wire'
      fullPath: '/api/multimodal-tool-result-wire'
      preLoaderRoute: typeof ApiMultimodalToolResultWireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mistral-strict-tool-null-wire': {
      id: '/api/mistral-strict-tool-null-wire'
      path: '/api/mistral-strict-tool-null-wire'
      fullPath: '/api/mistral-strict-tool-null-wire'
      preLoaderRoute: typeof ApiMistralStrictToolNullWireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/middleware-test': {
      id: '/api/middleware-test'
      path: '/api/middleware-test'
      fullPath: '/api/middleware-test'
      preLoaderRoute: typeof ApiMiddlewareTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/message-ids': {
      id: '/api/message-ids'
      path: '/api/message-ids'
      fullPath: '/api/message-ids'
      preLoaderRoute: typeof ApiMessageIdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp-test': {
      id: '/api/mcp-test'
      path: '/api/mcp-test'
      fullPath: '/api/mcp-test'
      preLoaderRoute: typeof ApiMcpTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp-status-test': {
      id: '/api/mcp-status-test'
      path: '/api/mcp-status-test'
      fullPath: '/api/mcp-status-test'
      preLoaderRoute: typeof ApiMcpStatusTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp-server': {
      id: '/api/mcp-server'
      path: '/api/mcp-server'
      fullPath: '/api/mcp-server'
      preLoaderRoute: typeof ApiMcpServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp-managed-test': {
      id: '/api/mcp-managed-test'
      path: '/api/mcp-managed-test'
      fullPath: '/api/mcp-managed-test'
      preLoaderRoute: typeof ApiMcpManagedTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp-lifecycle-test': {
      id: '/api/mcp-lifecycle-test'
      path: '/api/mcp-lifecycle-test'
      fullPath: '/api/mcp-lifecycle-test'
      preLoaderRoute: typeof ApiMcpLifecycleTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp-apps-server': {
      id: '/api/mcp-apps-server'
      path: '/api/mcp-apps-server'
      fullPath: '/api/mcp-apps-server'
      preLoaderRoute: typeof ApiMcpAppsServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp-apps-chat': {
      id: '/api/mcp-apps-chat'
      path: '/api/mcp-apps-chat'
      fullPath: '/api/mcp-apps-chat'
      preLoaderRoute: typeof ApiMcpAppsChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp-apps-call': {
      id: '/api/mcp-apps-call'
      path: '/api/mcp-apps-call'
      fullPath: '/api/mcp-apps-call'
      preLoaderRoute: typeof ApiMcpAppsCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/max-tool-calls-wire': {
      id: '/api/max-tool-calls-wire'
      path: '/api/max-tool-calls-wire'
      fullPath: '/api/max-tool-calls-wire'
      preLoaderRoute: typeof ApiMaxToolCallsWireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lazy-tools-wire': {
      id: '/api/lazy-tools-wire'
      path: '/api/lazy-tools-wire'
      fullPath: '/api/lazy-tools-wire'
      preLoaderRoute: typeof ApiLazyToolsWireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/join-run-client-tool': {
      id: '/api/join-run-client-tool'
      path: '/api/join-run-client-tool'
      fullPath: '/api/join-run-client-tool'
      preLoaderRoute: typeof ApiJoinRunClientToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interrupts-test': {
      id: '/api/interrupts-test'
      path: '/api/interrupts-test'
      fullPath: '/api/interrupts-test'
      preLoaderRoute: typeof ApiInterruptsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image': {
      id: '/api/image'
      path: '/api/image'
      fullPath: '/api/image'
      preLoaderRoute: typeof ApiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generation-persistence-server': {
      id: '/api/generation-persistence-server'
      path: '/api/generation-persistence-server'
      fullPath: '/api/generation-persistence-server'
      preLoaderRoute: typeof ApiGenerationPersistenceServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generation-persistence-resume': {
      id: '/api/generation-persistence-resume'
      path: '/api/generation-persistence-resume'
      fullPath: '/api/generation-persistence-resume'
      preLoaderRoute: typeof ApiGenerationPersistenceResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gemini-native-image-wire': {
      id: '/api/gemini-native-image-wire'
      path: '/api/gemini-native-image-wire'
      fullPath: '/api/gemini-native-image-wire'
      preLoaderRoute: typeof ApiGeminiNativeImageWireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gemini-image-ga-models': {
      id: '/api/gemini-image-ga-models'
      path: '/api/gemini-image-ga-models'
      fullPath: '/api/gemini-image-ga-models'
      preLoaderRoute: typeof ApiGeminiImageGaModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/foreign-interrupt': {
      id: '/api/foreign-interrupt'
      path: '/api/foreign-interrupt'
      fullPath: '/api/foreign-interrupt'
      preLoaderRoute: typeof ApiForeignInterruptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/embedding': {
      id: '/api/embedding'
      path: '/api/embedding'
      fullPath: '/api/embedding'
      preLoaderRoute: typeof ApiEmbeddingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/durable-takeover': {
      id: '/api/durable-takeover'
      path: '/api/durable-takeover'
      fullPath: '/api/durable-takeover'
      preLoaderRoute: typeof ApiDurableTakeoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/durable-delivery': {
      id: '/api/durable-delivery'
      path: '/api/durable-delivery'
      fullPath: '/api/durable-delivery'
      preLoaderRoute: typeof ApiDurableDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/devtools-memory': {
      id: '/api/devtools-memory'
      path: '/api/devtools-memory'
      fullPath: '/api/devtools-memory'
      preLoaderRoute: typeof ApiDevtoolsMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/byok-chat': {
      id: '/api/byok-chat'
      path: '/api/byok-chat'
      fullPath: '/api/byok-chat'
      preLoaderRoute: typeof ApiByokChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/byteplus-seedance-1080p-wire': {
      id: '/api/byteplus-seedance-1080p-wire'
      path: '/api/byteplus-seedance-1080p-wire'
      fullPath: '/api/byteplus-seedance-1080p-wire'
      preLoaderRoute: typeof ApiByteplusSeedance1080pWireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio': {
      id: '/api/audio'
      path: '/api/audio'
      fullPath: '/api/audio'
      preLoaderRoute: typeof ApiAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/arktype-tool-wire': {
      id: '/api/arktype-tool-wire'
      path: '/api/arktype-tool-wire'
      fullPath: '/api/arktype-tool-wire'
      preLoaderRoute: typeof ApiArktypeToolWireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/anthropic-structured-usage': {
      id: '/api/anthropic-structured-usage'
      path: '/api/anthropic-structured-usage'
      fullPath: '/api/anthropic-structured-usage'
      preLoaderRoute: typeof ApiAnthropicStructuredUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/anthropic-skills-wire': {
      id: '/api/anthropic-skills-wire'
      path: '/api/anthropic-skills-wire'
      fullPath: '/api/anthropic-skills-wire'
      preLoaderRoute: typeof ApiAnthropicSkillsWireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/anthropic-bug-test': {
      id: '/api/anthropic-bug-test'
      path: '/api/anthropic-bug-test'
      fullPath: '/api/anthropic-bug-test'
      preLoaderRoute: typeof ApiAnthropicBugTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$provider/$feature': {
      id: '/$provider/$feature'
      path: '/$provider/$feature'
      fullPath: '/$provider/$feature'
      preLoaderRoute: typeof ProviderFeatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video/stream': {
      id: '/api/video/stream'
      path: '/stream'
      fullPath: '/api/video/stream'
      preLoaderRoute: typeof ApiVideoStreamRouteImport
      parentRoute: typeof ApiVideoRoute
    }
    '/api/tts/stream': {
      id: '/api/tts/stream'
      path: '/stream'
      fullPath: '/api/tts/stream'
      preLoaderRoute: typeof ApiTtsStreamRouteImport
      parentRoute: typeof ApiTtsRoute
    }
    '/api/transcription/stream': {
      id: '/api/transcription/stream'
      path: '/stream'
      fullPath: '/api/transcription/stream'
      preLoaderRoute: typeof ApiTranscriptionStreamRouteImport
      parentRoute: typeof ApiTranscriptionRoute
    }
    '/api/image/stream': {
      id: '/api/image/stream'
      path: '/stream'
      fullPath: '/api/image/stream'
      preLoaderRoute: typeof ApiImageStreamRouteImport
      parentRoute: typeof ApiImageRoute
    }
    '/api/audio/stream': {
      id: '/api/audio/stream'
      path: '/stream'
      fullPath: '/api/audio/stream'
      preLoaderRoute: typeof ApiAudioStreamRouteImport
      parentRoute: typeof ApiAudioRoute
    }
  }
}

interface ApiAudioRouteChildren {
  ApiAudioStreamRoute: typeof ApiAudioStreamRoute
}

const ApiAudioRouteChildren: ApiAudioRouteChildren = {
  ApiAudioStreamRoute: ApiAudioStreamRoute,
}

const ApiAudioRouteWithChildren = ApiAudioRoute._addFileChildren(
  ApiAudioRouteChildren,
)

interface ApiImageRouteChildren {
  ApiImageStreamRoute: typeof ApiImageStreamRoute
}

const ApiImageRouteChildren: ApiImageRouteChildren = {
  ApiImageStreamRoute: ApiImageStreamRoute,
}

const ApiImageRouteWithChildren = ApiImageRoute._addFileChildren(
  ApiImageRouteChildren,
)

interface ApiTranscriptionRouteChildren {
  ApiTranscriptionStreamRoute: typeof ApiTranscriptionStreamRoute
}

const ApiTranscriptionRouteChildren: ApiTranscriptionRouteChildren = {
  ApiTranscriptionStreamRoute: ApiTranscriptionStreamRoute,
}

const ApiTranscriptionRouteWithChildren =
  ApiTranscriptionRoute._addFileChildren(ApiTranscriptionRouteChildren)

interface ApiTtsRouteChildren {
  ApiTtsStreamRoute: typeof ApiTtsStreamRoute
}

const ApiTtsRouteChildren: ApiTtsRouteChildren = {
  ApiTtsStreamRoute: ApiTtsStreamRoute,
}

const ApiTtsRouteWithChildren =
  ApiTtsRoute._addFileChildren(ApiTtsRouteChildren)

interface ApiVideoRouteChildren {
  ApiVideoStreamRoute: typeof ApiVideoStreamRoute
}

const ApiVideoRouteChildren: ApiVideoRouteChildren = {
  ApiVideoStreamRoute: ApiVideoStreamRoute,
}

const ApiVideoRouteWithChildren = ApiVideoRoute._addFileChildren(
  ApiVideoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ByokRoute: ByokRoute,
  ChatClientDefaultBridgeRoute: ChatClientDefaultBridgeRoute,
  DevtoolsChatRoute: DevtoolsChatRoute,
  DevtoolsGenerationHooksRoute: DevtoolsGenerationHooksRoute,
  DevtoolsMemoryRoute: DevtoolsMemoryRoute,
  DevtoolsRouteARoute: DevtoolsRouteARoute,
  DevtoolsRouteBRoute: DevtoolsRouteBRoute,
  DevtoolsStructuredRoute: DevtoolsStructuredRoute,
  DevtoolsToolsRoute: DevtoolsToolsRoute,
  ForeignInterruptRoute: ForeignInterruptRoute,
  GenerationPersistenceResumeRoute: GenerationPersistenceResumeRoute,
  GenerationPersistenceServerRoute: GenerationPersistenceServerRoute,
  InterruptsTestRoute: InterruptsTestRoute,
  JoinRunClientToolRoute: JoinRunClientToolRoute,
  MarkdownCjkRoute: MarkdownCjkRoute,
  MiddlewareTestRoute: MiddlewareTestRoute,
  PersistenceDurabilityRoute: PersistenceDurabilityRoute,
  ToolsTestRoute: ToolsTestRoute,
  WebsocketAdapterRoute: WebsocketAdapterRoute,
  ProviderFeatureRoute: ProviderFeatureRoute,
  ApiAnthropicBugTestRoute: ApiAnthropicBugTestRoute,
  ApiAnthropicSkillsWireRoute: ApiAnthropicSkillsWireRoute,
  ApiAnthropicStructuredUsageRoute: ApiAnthropicStructuredUsageRoute,
  ApiArktypeToolWireRoute: ApiArktypeToolWireRoute,
  ApiAudioRoute: ApiAudioRouteWithChildren,
  ApiByokChatRoute: ApiByokChatRoute,
  ApiByteplusSeedance1080pWireRoute: ApiByteplusSeedance1080pWireRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDevtoolsMemoryRoute: ApiDevtoolsMemoryRoute,
  ApiDurableDeliveryRoute: ApiDurableDeliveryRoute,
  ApiDurableTakeoverRoute: ApiDurableTakeoverRoute,
  ApiEmbeddingRoute: ApiEmbeddingRoute,
  ApiForeignInterruptRoute: ApiForeignInterruptRoute,
  ApiGeminiImageGaModelsRoute: ApiGeminiImageGaModelsRoute,
  ApiGeminiNativeImageWireRoute: ApiGeminiNativeImageWireRoute,
  ApiGenerationPersistenceResumeRoute: ApiGenerationPersistenceResumeRoute,
  ApiGenerationPersistenceServerRoute: ApiGenerationPersistenceServerRoute,
  ApiImageRoute: ApiImageRouteWithChildren,
  ApiInterruptsTestRoute: ApiInterruptsTestRoute,
  ApiJoinRunClientToolRoute: ApiJoinRunClientToolRoute,
  ApiLazyToolsWireRoute: ApiLazyToolsWireRoute,
  ApiMaxToolCallsWireRoute: ApiMaxToolCallsWireRoute,
  ApiMcpAppsCallRoute: ApiMcpAppsCallRoute,
  ApiMcpAppsChatRoute: ApiMcpAppsChatRoute,
  ApiMcpAppsServerRoute: ApiMcpAppsServerRoute,
  ApiMcpLifecycleTestRoute: ApiMcpLifecycleTestRoute,
  ApiMcpManagedTestRoute: ApiMcpManagedTestRoute,
  ApiMcpServerRoute: ApiMcpServerRoute,
  ApiMcpStatusTestRoute: ApiMcpStatusTestRoute,
  ApiMcpTestRoute: ApiMcpTestRoute,
  ApiMessageIdsRoute: ApiMessageIdsRoute,
  ApiMiddlewareTestRoute: ApiMiddlewareTestRoute,
  ApiMistralStrictToolNullWireRoute: ApiMistralStrictToolNullWireRoute,
  ApiMultimodalToolResultWireRoute: ApiMultimodalToolResultWireRoute,
  ApiNonStreamingRunErrorRoute: ApiNonStreamingRunErrorRoute,
  ApiOpenaiCompletedResponseTextRoute: ApiOpenaiCompletedResponseTextRoute,
  ApiOpenaiShellSkillsWireRoute: ApiOpenaiShellSkillsWireRoute,
  ApiOpenaiStrictToolNullWireRoute: ApiOpenaiStrictToolNullWireRoute,
  ApiOpenaiUsageDetailsRoute: ApiOpenaiUsageDetailsRoute,
  ApiOpenrouterCostRoute: ApiOpenrouterCostRoute,
  ApiOpenrouterJsonObjectWireRoute: ApiOpenrouterJsonObjectWireRoute,
  ApiOpenrouterReasoningWireRoute: ApiOpenrouterReasoningWireRoute,
  ApiOpenrouterWebToolsWireRoute: ApiOpenrouterWebToolsWireRoute,
  ApiOtelMediaRoute: ApiOtelMediaRoute,
  ApiOtelTranscriptionRoute: ApiOtelTranscriptionRoute,
  ApiOtelUsageRoute: ApiOtelUsageRoute,
  ApiPersistenceDurabilityRoute: ApiPersistenceDurabilityRoute,
  ApiProviderToolDispatchWireRoute: ApiProviderToolDispatchWireRoute,
  ApiSandboxDurabilityRoute: ApiSandboxDurabilityRoute,
  ApiSandboxFilePersistenceRoute: ApiSandboxFilePersistenceRoute,
  ApiSandboxToolHistoryRoute: ApiSandboxToolHistoryRoute,
  ApiSummarizeRoute: ApiSummarizeRoute,
  ApiToolCallLifecycleWireRoute: ApiToolCallLifecycleWireRoute,
  ApiToolsTestRoute: ApiToolsTestRoute,
  ApiTranscriptionRoute: ApiTranscriptionRouteWithChildren,
  ApiTtsRoute: ApiTtsRouteWithChildren,
  ApiVideoRoute: ApiVideoRouteWithChildren,
  ProviderIndexRoute: ProviderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
